TrajectoryPlannerROS:
  max_vel_y: 0
  max_vel_x: 0.5
  min_vel_x: 0.01
  max_vel_theta: 1.5
  min_in_place_vel_theta: 0.01

  acc_lim_theta: 1.0
  acc_lim_x: 0.5


  holonomic_robot: false
  
  
  sim_time: 2.0
  
  vx_samples: 10
  vy_samples: 0
